name: 🌤 Hourly Data Ingestion to Hopsworks

on:
  schedule:
    # ⏰ Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:  # allow manual trigger too

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install hopsworks requests pandas python-dotenv

      # 4️⃣ Set environment variables (from GitHub Secrets)
      - name: Set environment variables
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          echo "OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}" >> $GITHUB_ENV
          echo "HOPSWORKS_API_KEY=${HOPSWORKS_API_KEY}" >> $GITHUB_ENV

      # 5️⃣ Run your ingestion script
      - name: Run hourly data ingestion
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python hourly_data_ingestion_2.py
