name: 🌤️ Hourly Data Ingestion to Hopsworks

on:
  workflow_dispatch:   # allows you to run manually from GitHub Actions tab
  schedule:
    - cron: "0 * * * *"   # runs every hour

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Debug structure (optional)
      - name: Debug repository structure
        run: |
          echo "📂 Listing files in workspace:"
          ls -R

      # 4️⃣ Install dependencies
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade hopsworks requests pandas python-dotenv

      # 5️⃣ Run ingestion script
      - name: Run hourly ingestion
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          echo "🚀 Starting data ingestion..."
          python hourly_data_ingestion_2.py
